yes
aphased/BingoPartyBot pull request #24
Opened 2024-09-28 19:27 UTC by jbanate

this all seems about right
- Added a cap to how fast crep can send messages at half a second
- Crep can now parse fractions of a second (!p ccrep 5 1.5)
- Copied the entirety of query and made !p test
- made interfaces.json shorter although idk if that would cause any issues

2024-09-28 19:50 UTC, Conutik requested changes

2024-09-28 19:50 UTC, Conutik commented on src/utils/Interfaces.mjs
> +  Owner, BotAccount: 5,
You can't do this in js, it'll give `Owner` as undefined

2024-09-28 19:50 UTC, Conutik commented on src/utils/Interfaces.mjs
> +  Splasher, Trusted: 2,
Same here

2024-09-29 13:32 UTC, jbanate commented
changed also new commit:

manually select playernames.json because help me
same with generalDatabase.json and package-lock.json

Added !p limbo
Fixed !p crep
Made !p crep and !p rep more user-friendly by telling the user how to use it if used incorrectly
Added reason arg for the following commands:
!p ban
!p close (Not functioning yet)
!p disband
!p kick
!p mute
!p drain
To use this, just put the reason after the command, for example: !p ban jbanate spamming
If no reason is provided, it will default to "No reason provided."
This will not show in-game (yet, idk whether to add it) and only logs in Discord

2024-09-30 08:28 UTC, Conutik commented on src/mineflayer/commands/party/Test.mjs
Why change from `misc` to `party` 😭

2024-09-30 08:30 UTC, Conutik commented on src/mineflayer/commands/party/Unban.mjs
Are you sure that the bot would be spawned in the lobby before running other commands?

2024-09-30 08:30 UTC, Conutik commented on src/mineflayer/commands/party/Ban.mjs
Same concern as unban

2024-09-30 09:11 UTC, merged